### ISSUE TITLE
username password deprecation

### ISSUE THREAD

**Issue by mathurin68** [cfalta/PowerShellArmoury#3]
FYI, 
On August 15th, 2020 at 00:42 (UTC) you used a password to access an endpoint through the GitHub API using TotallyLegit:

https://api.github.com/repositories/4456049

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

P.S. love this!

**Comment by cfalta** [comment]
Hi,
thanks for your comment. Though it is only briefly mentioned in the readme, I always assumed that the Github API is only used with username and personal access token since this is the only way to do it with MFA enabled.
Therefore I would suggest you create yourself a personal access token as described here: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
You can just enter this instead of your password in the authentication dialog.

Thanks for using PSArmoury and let me know if you have any other suggestions for improvements :-)

**Comment by mathurin68** [comment]
Hahaha omg I'm a moron I turned off my MFA to use this.  Thank you so much!
